site_name: Samuel_mkdocs

nav:
    - Practica LAMP en RHEL: LAMP_RHEL.md
    - Practica LAMP en UBUNTU: LAMP_UBUNTU.md


theme: 
  name: material
  palette:
    primary: purple
    accent: pink
  logo: images/S.png
  font: 
   text: Fredoka
   code: Fredoka


  