site_name: Samuel_mkdocs

nav:
    - Practica LAMP en ubuntu: LAMP_ubuntu.md
    - Practica LAMP en RHEL: LAMP_rhel.md


theme: 
  name: material
  palette:
    primary: purple
    accent: pink
  logo: images/S.png
  font: 
   text: Fredoka
   code: Fredoka


  